language: java

jdk:
  - oraclejdk8

notifications:
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd frontend
  - nvm install v4
  - nvm use v4
  - npm install

#Add other test runs here by adding && and running commands
# to change to the correct dir and run the tests
# (for example for the test of the node)
script: cd ../backend && mvn test && cd ../frontend && npm test
env:
  - BUILD_PR_BRANCH=true
  - BUILD_PR_BRANCH=false
matrix:
  allow_failures:
    - env:
      - BUILD_PR_BRANCH=true
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="
